name: CI

on:
  pull_request:

jobs:
  ci:
    name: Run - yarn ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['typecheck', 'lint', 'test']
    steps:
      - name: Setup
        uses: ./.github/actions/setup/action.yml
      - name: Run command - ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
