name: Release

on:
  workflow_call:
    inputs:
      prerelease:
        required: true
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      prerelease:
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ inputs.prerelease == true && ' --pre-release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
          RELEASE: ${{ env.RELEASE }}
        run: yarn semantic-release
