name: Release

on:
  push:
    branches:
      - main
      - 'pre-release'

permissions:
      attestations: write
      contents: write
      deployments: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.ref_name == 'pre-release' && ' --pre-release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
          RELEASE: ${{ env.RELEASE }}
        run: yarn semantic-release
