name: Release

on:
  workflow_call:
    inputs:
      prerelease:
        required: true
        type: boolean
        default: false
      # release_type:
      #   required: true
      #   type: string
      #   default: patch

  workflow_dispatch:
    inputs:
      prerelease:
        required: false
        type: boolean
        default: false
      # release_type:
      #   required: true
      #   type: choice
      #   options:
      #     - major
      #     - minor
      #     - patch
      #   default: patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.prerelease == 'true' && 'prerelease' || 'release' }}
      RELEASE: ${{ inputs.prerelease == 'true' && ' --pre-release' }}
    steps:
      # TODO: verify if version is different than main branch, if not then version bump
      - name: Setup
        uses: ./.github/actions/setup/action.yml
        with:
          branch: ${{ env.BRANCH }}
      - name: Package
        run: yarn vsce package${{env.RELEASE}}
      - run: |
          VSIX_PATH=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)
          echo "VSIX_PATH=$VSIX_PATH" >> $GITHUB_ENV
          echo "VSIX_NAME=$(basename $VSIX_PATH)" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.VSIX_PATH }}
          name: ${{ env.VSIX_NAME }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{secrets.MARKETPLACE_ACCESS_TOKEN}}

        run: yarn vsce publish${{env.RELEASE}} -p ${{env.VSCE_PAT}}
      - name: Merge
        uses: ./.github/actions/merge/action.yml
        with:
          base: main
          branch: ${{ env.BRANCH }}
